### ISSUE TITLE
go.exe will not run on python

### ISSUE THREAD

**Issue by RipVanWenkle** [woogers/mjgl-tools#1]
When running go.exe on Windows 7 the exe will run into a system error with the following error messages:

The program can't start because api-ms-win-core-l1-1.0.dll is missing from your computer. Try reinstalling the program to fix this problem.
 
This is an error for pretty much all python.exe compiled in the latest python: https://bugs.python.org/issue40740

**Comment by woogers** [comment]
Will cut a new dist using Python 3.8.

**Comment by woogers** [comment]
Windows 7 support is here, in theory. I can't test it though, so 💯
