### ISSUE TITLE
Formating of points graph

### ISSUE THREAD

**Issue by Anonj0008** [woogers/mjgl-tools#6]
Would be helpful if the graph drawn up under the "Rankings" scene wasn't transparent, makes for easier reading and tracing of team rankings against the background. Alternatively change background to plain white

**Comment by RipVanWenkle** [comment]
Future releases will allow the user to specify whether the background for the graph will be transparent or a solid colour. Alternatively, users can create a color element underneath the graph to act as a background as a stop-gap measure.

**Comment by woogers** [comment]
This is pretty easy to handle, we can add it to the config file. But it's probably not worth putting out a new release for on its own, since there's a workaround.

**Comment by woogers** [comment]
Oh wait, I fixed this a while ago
