### ISSUE TITLE
Finals v1.2.1

### ISSUE THREAD

**Issue by watterle** [woogers/mjgl-tools#7]
![Screenshot 2021-06-03 14-46-58](https://user-images.githubusercontent.com/49875739/120647371-d3005280-c47a-11eb-9ab0-5a67f5ccdecf.png)
Nyakuza is inserted 2 times instead of AUTISM. And the config file is set on woogers's PC, but it's not like you're supposed to overwrite it so it doesn't matter much.

**Comment by woogers** [comment]
a new fix for you~
https://github.com/woogers/mjgl-tools/releases/tag/v1.2.2
